import localFont from "next/font/local";
import "./globals.css";
import type { Metadata } from "next";
import { Header } from "@/components/header";

const halvarBreit = localFont({
  src: [
    {
      path: "../../public/fonts/HalvarBreitt2-XBd.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/HalvarBreitt2-XBd.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/HalvarBreitt2-XBd.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/HalvarBreitt2-XBd.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-halvar",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${halvarBreit.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
